# snakemake --resources mem_mb=700000 --slurm --default-resources \
# slurm_account=ec85 runtime=4320 mem_mb_per_cpu=21000 cpus_per_task=4 \
# --use-conda --cluster-cancel scancel --keep-going -j unlimited

# region:
# snakemake --resources mem_mb=700000 --slurm --default-resources \
# slurm_account=ec85 runtime=30 mem_mb_per_cpu=1100 cpus_per_task=4 \
# --use-conda --cluster-cancel scancel --keep-going -j unlimited

paths:
  gams: /fp/projects01/ec85/.bin/gams/gams41.5_linux_x64_64_sfx/
  shared_input: /fp/projects01/ec85/models/max/special_issue/shared_input/
  abs_shared_code: /fp/projects01/ec85/models/group/joint_wind/highRES-model/resources/4_model_code_shared/
  abs_con: /cluster/work/projects/ec85/joint-wind/koenandaleksera5/
  resultsdir: /cluster/work/projects/ec85/nuance/results/