target: "results.db.compressed"

paths:
  gams: /fp/projects01/ec85/.bin/gams/gams49.4_linux_x64_64_sfx/
  shared_input: C:/Users/Tobias/Downloads/NUANCE model/resources/shared_input/
  abs_shared_code: C:/Users/Tobias/Downloads/NUANCE model/resources/4_model_code_shared/
  abs_con: C:/Users/Tobias/Downloads/NUANCE model/resources/bias_correct_wind/
  resultsdir: C:/Users/Tobias/Downloads/NUANCE model/results/

inputs:
  year: "2010"
  spatial_res: "region"
  cutoff_solar: 0.09
  cutoff_onwind: 0.15
  cutoff_offwind: 0.20
  hydro_res_min: 0.2
  transmission_fom_percent: 0.02
  EV: "ON"
  total_imports: 0

scenarios:
  EV_flex: ["0","5","10","15","20","25","30","35","40","45","50","55","60","65","70","75","80","85","90","95","100"]
  V2G: ["ON","OFF"]
